apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-pgdata
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 
    path: /k8s/app-files/kong/pgdata
    user: kong
    secretRef:
      name: kong-secret
  persistentVolumeReclaimPolicy: Retain
