apiVersion: v1
kind: PersistentVolume
metadata: 
 name: "statefulset-pgdata"
 labels: 
  name: "statefulset-pgdata"
spec: 
 capacity: 
  storage: "10Gi"
 accessModes: ["ReadWriteMany"]
 hostPath: 
  path: "/Users/hawick/pgdata-0"
 persistentVolumeReclaimPolicy: Retain
