apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 1.1.1.1:6789
    path: /
    user: admin
    secretRef:
      name: redis-ceph-secret
  persistentVolumeReclaimPolicy: Recycle
