apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
spec:
  containers:
    - name: master
      image: hawickhuang/ha-redis:4.0.6-1.0.0
      imagePullPolicy: Always
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /data
          name: data
    - name: sentinel
      image: hawickhuang/ha-redis:4.0.6-1.0.0
      imagePullPolicy: Always
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: redis-pvc
