apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  #namespace: redis
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteMany
  volumeName: redis-pv
  resources:
    requests:
      storage: 50Gi
